FROM --platform=$BUILDPLATFORM rust:alpine

RUN apk add --no-cache \
    bash \
    binutils \
    build-base \
    ca-certificates \
    coreutils \
    file \
    linux-headers \
    musl-dev \
    tar

WORKDIR /work

ENV CARGO_HOME=/cargo
ENV CARGO_TARGET_DIR=/cargo-target
ENV PATH=/cargo/bin:/usr/local/cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

CMD ["sh"]
